import type {
  ExerciseDefinition,
} from "./types";

// ============================================================
// Built-In Exercise Library
// ============================================================
//
// Programming values below come from the Fitness OS
// spreadsheet DATA_Exercises table.
//
// Exercises that existed in the app but were not defined
// in the spreadsheet are preserved without progression
// settings. We can configure those separately later.
//
// Metric model:
//
// resistanceType
//   None       = bodyweight / no external resistance
//   Weight     = conventional external load
//   Assistance = external assistance
//   Band       = resistance-band loading
//
// performanceType
//   Reps       = performance measured in repetitions
//   Duration   = performance measured in seconds
//
// progressionType is temporarily retained for backwards
// compatibility with the existing progression engine.
// ============================================================

export const exerciseLibrary: ExerciseDefinition[] = [
  // ==========================================================
  // Chest
  // ==========================================================

  {
    id: "chest-press-machine",
    name: "Chest Press Machine",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Adjust the seat so the handles begin around mid-chest and your feet stay planted.",
        "Set your shoulder blades gently against the pad and choose a load you can control.",
      ],
      execution: [
        "Press the handles forward without shrugging or lifting your back from the pad.",
        "Return slowly until you feel a comfortable chest stretch, then repeat.",
      ],
      techniqueCues: ["Keep wrists stacked over forearms.", "Exhale through the press and keep the ribs controlled."],
      commonMistakes: ["Setting the seat too low and pressing toward the face.", "Letting the weight stack slam between repetitions."],
      safetyConsiderations: ["Use a pain-free shoulder range and stop if pressing causes sharp pain."],
      regressionExerciseIds: ["push-ups"],
      progressionExerciseIds: ["dumbbell-chest-press", "barbell-bench-press"],
    },
  },
  {
    id: "incline-chest-press-machine",
    name: "Incline Chest Press Machine",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Adjust the seat so the handles begin near the upper chest, not above the shoulders.",
        "Plant your feet and keep your head and upper back supported.",
      ],
      execution: [
        "Press up and forward through a comfortable path while keeping the shoulders down.",
        "Lower with control until the elbows reach a comfortable depth.",
      ],
      techniqueCues: ["Keep forearms aligned with the handles.", "Maintain contact with the back pad."],
      commonMistakes: ["Shrugging toward the ears.", "Overarching the low back to finish the press."],
      safetyConsiderations: ["Reduce the range or load if the front of the shoulder feels pinched."],
      regressionExerciseIds: ["chest-press-machine"],
      progressionExerciseIds: ["incline-dumbbell-press"],
    },
  },
  {
    id: "dumbbell-chest-press",
    name: "Dumbbell Chest Press",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["Dumbbells", "Bench"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // ----------------------------------------------------------
  // Push-Up Progression
  // ----------------------------------------------------------

  {
    id: "push-ups",
    name: "Push-Ups",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 8,
    repMax: 15,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Place your hands just outside shoulder width and form a straight line from head to heels.",
        "Brace your trunk before the first repetition.",
      ],
      execution: [
        "Lower your chest under control while keeping your elbows angled slightly back.",
        "Press the floor away without letting your hips sag or rise first.",
      ],
      techniqueCues: ["Keep head, ribs, hips, and heels moving as one unit.", "Spread the floor with your hands for shoulder stability."],
      commonMistakes: ["Flaring the elbows straight sideways.", "Losing trunk tension before the chest reaches the bottom."],
      safetyConsiderations: ["Elevate the hands to reduce difficulty if you cannot maintain position or have wrist discomfort."],
      progressionExerciseIds: ["feet-elevated-push-ups", "weighted-push-ups"],
    },
    nextVariationId:
      "feet-elevated-push-ups",
  },
  {
    id: "feet-elevated-push-ups",
    name: "Feet-Elevated Push-Ups",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["Bodyweight", "Bench"],
    sets: 3,
    repMin: 8,
    repMax: 15,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
    nextVariationId:
      "weighted-push-ups",
  },
  {
    id: "weighted-push-ups",
    name: "Weighted Push-Ups",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // Not defined in the spreadsheet.
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["Barbell", "BarbellRack", "Bench"],
    sets: 3,
    repMin: 6,
    repMax: 10,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["Dumbbells", "Bench"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "chest-fly",
    name: "Pec Deck Machine",
    category: "Chest",
    movementRoles: ["ChestIsolation"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "cable-fly",
    name: "Cable Fly",
    category: "Chest",
    movementRoles: ["ChestIsolation"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "dumbbell-fly",
    name: "Dumbbell Fly",
    category: "Chest",
    movementRoles: ["ChestIsolation"],
    requiredEquipment: ["Dumbbells", "Bench"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // ==========================================================
  // Back
  // ==========================================================

  {
    id: "seated-row",
    name: "Seated Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Set the seat so you can reach the handles with a tall torso and relaxed shoulders.",
        "Plant your feet and brace lightly before pulling.",
      ],
      execution: [
        "Drive your elbows back without leaning away from the pad or rounding forward.",
        "Return the weight under control until your arms are long.",
      ],
      techniqueCues: ["Keep the shoulders away from the ears.", "Pause briefly when the elbows reach the torso."],
      commonMistakes: ["Using a large torso swing.", "Pulling past a comfortable shoulder position."],
      safetyConsiderations: ["Reduce load or range if the front of the shoulder becomes irritated."],
      regressionExerciseIds: ["band-row"],
      progressionExerciseIds: ["one-arm-dumbbell-row", "barbell-row"],
    },
  },
  {
    id: "cable-row",
    name: "Cable Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "one-arm-dumbbell-row",
    name: "One-Arm Dumbbell Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["Dumbbells", "Bench"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    repCounting: "PerSide",
  },
  {
    id: "backpack-row",
    name: "Backpack Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
  },
  {
    id: "band-row",
    name: "Band Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["ResistanceBands"],
    sets: 3,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Anchor the band securely around mid-torso height and step back until it is lightly tensioned.",
        "Stand or sit tall with the arms extended and shoulders relaxed.",
      ],
      execution: [
        "Pull the elbows behind you while bringing the hands toward the lower ribs.",
        "Pause briefly, then return until the arms are long without letting the shoulders roll forward.",
      ],
      techniqueCues: ["Keep the ribs stacked over the pelvis.", "Drive the elbows back instead of shrugging."],
      commonMistakes: ["Leaning backward to finish the pull.", "Allowing the band to snap the arms forward."],
      safetyConsiderations: ["Confirm the anchor and band are undamaged before loading them."],
      progressionExerciseIds: ["seated-row", "cable-row"],
    },
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    category: "Back",
    movementRoles: ["VerticalPull"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Secure your thighs beneath the pad and take a grip that keeps the wrists comfortable.",
        "Sit tall with the arms long and shoulders away from the ears.",
      ],
      execution: [
        "Drive the elbows down as the bar travels toward the upper chest.",
        "Return overhead under control without losing your seated position.",
      ],
      techniqueCues: ["Think elbows toward your back pockets.", "Use only a small natural torso lean."],
      commonMistakes: ["Pulling the bar behind the neck.", "Turning the repetition into a large backward swing."],
      safetyConsiderations: ["Use a grip and range that do not cause shoulder or elbow pain."],
      regressionExerciseIds: ["band-pulldown"],
      progressionExerciseIds: ["assisted-pull-up"],
    },
  },
  {
    id: "assisted-pull-up",
    name: "Assisted Pull-Up",
    category: "Back",
    movementRoles: ["VerticalPull"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Assistance",
    resistanceType: "Assistance",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Select enough assistance to complete controlled repetitions and enter the platform carefully.",
        "Set a comfortable grip and begin with the arms long and trunk braced.",
      ],
      execution: [
        "Pull the elbows down until the upper chest approaches the handles.",
        "Lower to the start under control before beginning the next repetition.",
      ],
      techniqueCues: ["Keep the legs quiet on the assistance pad.", "Lead with the chest rather than craning the neck."],
      commonMistakes: ["Using momentum from the knees.", "Dropping quickly into the bottom position."],
      safetyConsiderations: ["Enter and exit the moving assistance platform using the machine supports."],
      regressionExerciseIds: ["lat-pulldown", "band-pulldown"],
    },
  },
  {
    id: "band-pulldown",
    name: "Band Pulldown",
    category: "Back",
    movementRoles: ["VerticalPull"],
    requiredEquipment: ["ResistanceBands"],
    requiredCapabilities: ["HighAnchor"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
  },

  // Not defined in the spreadsheet.
  {
    id: "barbell-row",
    name: "Barbell Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["Barbell"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // ==========================================================
  // Shoulders
  // ==========================================================

  {
    id: "shoulder-press-machine",
    name: "Shoulder Press Machine",
    category: "Shoulders",
    movementRoles: ["VerticalPush"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Adjust the seat so the handles begin near shoulder height and your back is supported.",
        "Choose a grip that lets your forearms remain close to vertical.",
      ],
      execution: [
        "Press overhead without shrugging or flaring the ribs.",
        "Lower slowly to a comfortable depth with the elbows beneath the hands.",
      ],
      techniqueCues: ["Keep the head neutral and ribs stacked.", "Finish with control rather than locking out forcefully."],
      commonMistakes: ["Arching away from the pad.", "Lowering farther than the shoulders comfortably allow."],
      safetyConsiderations: ["Stop or shorten the range if overhead pressing causes pinching or sharp pain."],
      regressionExerciseIds: ["band-shoulder-press"],
      progressionExerciseIds: ["dumbbell-shoulder-press", "overhead-press"],
    },
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    category: "Shoulders",
    movementRoles: ["VerticalPush"],
    requiredEquipment: ["Dumbbells"],
    sets: 2,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "band-shoulder-press",
    name: "Band Shoulder Press",
    category: "Shoulders",
    movementRoles: ["VerticalPush"],
    requiredEquipment: ["ResistanceBands"],
    sets: 2,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Stand on the middle of the band with even tension and bring the handles to shoulder height.",
        "Brace your trunk with wrists stacked over the forearms.",
      ],
      execution: [
        "Press overhead until the arms are long without forcing the shoulders upward.",
        "Lower the hands to shoulder height under control.",
      ],
      techniqueCues: ["Keep the ribs down as the arms rise.", "Press evenly through both hands."],
      commonMistakes: ["Arching the low back to gain range.", "Standing on the band unevenly."],
      safetyConsiderations: ["Inspect the band and keep it clear of the face throughout the set."],
      progressionExerciseIds: ["shoulder-press-machine", "dumbbell-shoulder-press"],
    },
  },
  {
    id: "lateral-raise-machine",
    name: "Lateral Raise Machine",
    category: "Shoulders",
    movementRoles: ["ShoulderAbduction"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 12,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Adjust the seat so the machine pivot is near shoulder height and the pads contact above the elbows.",
        "Sit tall with your shoulders relaxed and feet planted.",
      ],
      execution: [
        "Raise the arms out to the sides until roughly shoulder height or your comfortable limit.",
        "Lower the pads slowly without letting the stack rest.",
      ],
      techniqueCues: ["Lead with the elbows.", "Keep the neck relaxed throughout the set."],
      commonMistakes: ["Shrugging to lift the weight.", "Using momentum or raising well above a comfortable shoulder range."],
      safetyConsiderations: ["Use a light, controlled load; lateral raises do not require heavy resistance."],
      regressionExerciseIds: ["dumbbell-lateral-raise"],
    },
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    category: "Shoulders",
    movementRoles: ["ShoulderAbduction"],
    requiredEquipment: ["Dumbbells"],
    sets: 2,
    repMin: 12,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    category: "Shoulders",
    movementRoles: ["RearShoulder"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 12,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "cable-face-pull",
    name: "Cable Face Pull",
    category: "Shoulders",
    movementRoles: ["RearShoulder"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 12,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // Not defined in the spreadsheet.
  {
    id: "overhead-press",
    name: "Barbell Overhead Press",
    category: "Shoulders",
    movementRoles: ["VerticalPush"],
    requiredEquipment: ["Barbell"],
    sets: 3,
    repMin: 6,
    repMax: 10,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // ==========================================================
  // Arms
  // ==========================================================

  {
    id: "biceps-curl-machine",
    name: "Biceps Curl Machine",
    category: "Arms",
    movementRoles: ["ElbowFlexion"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Adjust the seat so the elbows align with the machine pivot and rest comfortably on the pad.",
        "Take the handles with neutral wrists and keep the upper arms supported.",
      ],
      execution: [
        "Curl the handles toward you without lifting the elbows from the pad.",
        "Lower slowly until the elbows are nearly straight, then repeat.",
      ],
      techniqueCues: ["Keep the shoulders relaxed.", "Use the same controlled range on every repetition."],
      commonMistakes: ["Lifting the elbows to finish the curl.", "Dropping quickly into the bottom position."],
      safetyConsiderations: ["Avoid forcefully locking the elbows at the bottom."],
      regressionExerciseIds: ["band-biceps-curl"],
      progressionExerciseIds: ["dumbbell-curl", "barbell-curl"],
    },
  },
  {
    id: "dumbbell-curl",
    name: "Dumbbell Curl",
    category: "Arms",
    movementRoles: ["ElbowFlexion"],
    requiredEquipment: ["Dumbbells"],
    sets: 2,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "triceps-press-machine",
    name: "Triceps Pushdown Machine",
    category: "Arms",
    movementRoles: ["ElbowExtension"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Adjust the seat and handles so your elbows stay close to your sides through the available range.",
        "Sit tall with the shoulders down and wrists neutral.",
      ],
      execution: [
        "Press the handles down by straightening the elbows without moving the upper arms.",
        "Return under control until you feel a comfortable bend at the elbows.",
      ],
      techniqueCues: ["Pin the upper arms beside the torso.", "Finish by extending the elbows, not the shoulders."],
      commonMistakes: ["Leaning body weight into the handles.", "Letting the elbows drift forward and back."],
      safetyConsiderations: ["Use a pain-free range and avoid forcefully snapping the elbows straight."],
      regressionExerciseIds: ["band-overhead-triceps-extension"],
      progressionExerciseIds: ["cable-pressdown", "seated-dip-machine"],
    },
  },
  {
    id: "cable-pressdown",
    name: "Cable Pressdown",
    category: "Arms",
    movementRoles: ["ElbowExtension"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  {
    id: "band-biceps-curl",
    name: "Band Biceps Curl",
    category: "Arms",
    movementRoles: ["ElbowFlexion"],
    requiredEquipment: ["ResistanceBands"],
    sets: 2,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
  },
  {
    id: "band-overhead-triceps-extension",
    name: "Band Overhead Triceps Extension",
    category: "Arms",
    movementRoles: ["ElbowExtension"],
    requiredEquipment: ["ResistanceBands"],
    requiredCapabilities: ["HighAnchor"],
    sets: 2,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
  },

  {
    id: "seated-dip-machine",
    name: "Seated Dip Machine",
    category: "Arms",
    movementRoles: ["ElbowExtension"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    category: "Arms",
    movementRoles: ["ElbowFlexion"],
    requiredEquipment: ["Barbell"],
    sets: 2,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // ==========================================================
  // Legs
  // ==========================================================

  {
    id: "leg-press",
    name: "Leg Press",
    category: "Legs",
    movementRoles: ["Squat", "SquatGlute"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 10,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Place your feet where your heels stay planted and your knees track with your toes.",
        "Set the seat so the starting depth is comfortable and your lower back stays supported.",
      ],
      execution: [
        "Lower the sled under control to your comfortable depth.",
        "Press through your whole foot without locking your knees hard at the top.",
      ],
      techniqueCues: ["Keep knees tracking with toes.", "Maintain even pressure through heel and forefoot."],
      commonMistakes: ["Allowing the pelvis to curl away from the pad at the bottom.", "Driving the knees inward during the press."],
      safetyConsiderations: ["Set and understand the machine safeties before loading it heavily."],
      regressionExerciseIds: ["goblet-squat"],
      progressionExerciseIds: ["hack-squat-pendulum-squat", "barbell-squat"],
    },
  },
  {
    id: "hack-squat-pendulum-squat",
    name: "Hack Squat / Pendulum Squat",
    category: "Legs",
    movementRoles: ["Squat", "SquatGlute"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 10,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Position your shoulders and back securely against the pads and place your feet where the heels stay down.",
        "Release the safety stops only after you are braced and stable.",
      ],
      execution: [
        "Bend the knees and hips together to descend through a comfortable range.",
        "Drive through the whole foot to stand without snapping the knees straight.",
      ],
      techniqueCues: ["Track the knees with the toes.", "Keep your trunk supported by the machine."],
      commonMistakes: ["Letting the heels lift.", "Descending deeper than you can control without the pelvis shifting."],
      safetyConsiderations: ["Confirm the safety stops and practice reracking before using a challenging load."],
      regressionExerciseIds: ["leg-press", "goblet-squat"],
      progressionExerciseIds: ["barbell-squat"],
    },
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    category: "Legs",
    movementRoles: ["Squat"],
    requiredEquipment: ["Dumbbells"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "reverse-lunge",
    name: "Reverse Lunge",
    category: "Legs",
    movementRoles: ["Squat"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
    repCounting: "PerSide",
    guidance: {
      setup: [
        "Stand tall with enough clear space to step backward.",
        "Brace your trunk and keep your front foot planted.",
      ],
      execution: [
        "Step back and lower both knees while keeping the front knee aligned with the toes.",
        "Drive through the front foot to return to standing before changing sides.",
      ],
      techniqueCues: ["Keep most of the working pressure through the front foot.", "Use a step length that lets both knees bend comfortably."],
      commonMistakes: ["Stepping onto a tightrope instead of maintaining hip-width balance.", "Pushing excessively from the back foot."],
      safetyConsiderations: ["Use a stable support or reduce depth if balance limits control."],
      progressionExerciseIds: ["goblet-squat"],
    },
  },
  {
    id: "leg-curl",
    name: "Seated Leg Curl",
    category: "Legs",
    movementRoles: ["KneeFlexion"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Align your knees with the machine pivot and place the lower pad just above the heels.",
        "Secure the thigh pad so your hips stay in the seat without uncomfortable pressure.",
      ],
      execution: [
        "Curl the pad down by bending the knees while keeping your hips still.",
        "Return slowly until the legs are nearly straight without letting the stack slam.",
      ],
      techniqueCues: ["Keep the toes relaxed.", "Pause briefly in the shortened position."],
      commonMistakes: ["Lifting the hips to move more weight.", "Allowing the return phase to pull the knees abruptly straight."],
      safetyConsiderations: ["Adjust the machine rather than training through pressure behind the knees."],
      regressionExerciseIds: ["band-leg-curl"],
      progressionExerciseIds: ["lying-leg-curl"],
    },
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl",
    category: "Legs",
    movementRoles: ["KneeFlexion"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "band-leg-curl",
    name: "Band Leg Curl",
    category: "Legs",
    movementRoles: ["KneeFlexion"],
    requiredEquipment: ["ResistanceBands"],
    requiredCapabilities: ["LowAnchor"],
    sets: 3,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
  },
  {
    id: "dumbbell-rdl",
    name: "Dumbbell RDL",
    category: "Legs",
    movementRoles: ["HipHinge"],
    requiredEquipment: ["Dumbbells"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Stand with the dumbbells close to your thighs, feet stable, and knees softly bent.",
        "Brace your trunk and set your shoulders before beginning the hinge.",
      ],
      execution: [
        "Push the hips backward while the dumbbells travel close to the legs.",
        "Stop when the hamstrings limit the hinge, then drive the hips forward to stand tall.",
      ],
      techniqueCues: ["Keep a long neutral spine.", "Let the hips move back rather than turning the exercise into a squat."],
      commonMistakes: ["Reaching the weights toward the floor by rounding the back.", "Letting the dumbbells drift away from the legs."],
      safetyConsiderations: ["Use a shorter range if you cannot maintain trunk position or feel strain in the low back."],
      regressionExerciseIds: ["band-good-morning", "glute-bridge"],
      progressionExerciseIds: ["romanian-deadlift"],
    },
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    category: "Legs",
    movementRoles: ["HipExtension"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Lie on your back with knees bent, feet planted about hip width, and heels near the hips.",
        "Brace lightly so the ribs stay settled before lifting.",
      ],
      execution: [
        "Drive through the feet and squeeze the glutes to lift the hips.",
        "Stop when the hips are extended without arching the low back, then lower with control.",
      ],
      techniqueCues: ["Keep the knees tracking over the feet.", "Think ribs down and belt buckle up."],
      commonMistakes: ["Finishing by arching the low back.", "Pushing mostly through the toes."],
      safetyConsiderations: ["Shorten the range if the movement causes low-back discomfort."],
      progressionExerciseIds: ["hip-thrust-machine"],
    },
  },
  {
    id: "hip-thrust-machine",
    name: "Hip Thrust Machine",
    category: "Legs",
    movementRoles: ["HipExtension"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "glute-kickback-machine",
    name: "Glute Kickback Machine",
    category: "Legs",
    movementRoles: ["HipExtension"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    repCounting: "PerSide",
  },
  {
    id: "band-good-morning",
    name: "Band Good Morning",
    category: "Legs",
    movementRoles: ["HipHinge"],
    requiredEquipment: ["ResistanceBands"],
    requiredCapabilities: ["FloorSpace"],
    sets: 3,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Stand securely on the band and loop it behind the upper back, not across the neck.",
        "Set the feet about hip width with soft knees and a braced trunk.",
      ],
      execution: [
        "Push the hips backward while keeping the spine long and the band secure.",
        "Stop at a controlled hamstring stretch, then drive the hips forward to stand tall.",
      ],
      techniqueCues: ["Keep pressure through the whole foot.", "Move the hips back instead of squatting down."],
      commonMistakes: ["Rounding the back to reach lower.", "Letting the band ride onto the neck."],
      safetyConsiderations: ["Inspect the band and keep it positioned across the upper back throughout."],
      progressionExerciseIds: ["dumbbell-rdl", "romanian-deadlift"],
    },
  },
  {
    id: "hip-abductor",
    name: "Hip Abductor",
    category: "Legs",
    movementRoles: ["HipStability"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 12,
    repMax: 20,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "side-lying-hip-abduction",
    name: "Side-Lying Hip Abduction",
    category: "Legs",
    movementRoles: ["HipStability"],
    requiredEquipment: ["Bodyweight", "YogaMat"],
    requiredCapabilities: ["FloorSpace"],
    sets: 2,
    repMin: 12,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
    repCounting: "PerSide",
  },
  {
    id: "side-lying-hip-adduction",
    name: "Side-Lying Hip Adduction",
    category: "Legs",
    movementRoles: ["Adduction"],
    requiredEquipment: ["Bodyweight", "YogaMat"],
    requiredCapabilities: ["FloorSpace"],
    sets: 2,
    repMin: 12,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
    repCounting: "PerSide",
  },
  {
    id: "hip-adductor",
    name: "Hip Adductor",
    category: "Legs",
    movementRoles: ["Adduction"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 12,
    repMax: 20,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // Not defined in the spreadsheet.
  {
    id: "barbell-squat",
    name: "Barbell Squat",
    category: "Legs",
    movementRoles: ["Squat", "SquatGlute"],
    requiredEquipment: ["Barbell", "BarbellRack"],
    sets: 3,
    repMin: 6,
    repMax: 10,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "romanian-deadlift",
    name: "Barbell Romanian Deadlift",
    category: "Legs",
    movementRoles: ["HipHinge"],
    requiredEquipment: ["Barbell"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "calf-raise",
    name: "Standing Calf Raise",
    category: "Legs",
    movementRoles: ["CalfRaise"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 12,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
  },
  {
    id: "standing-calf-raise-machine",
    name: "Standing Calf Raise Machine",
    category: "Legs",
    movementRoles: ["CalfRaise"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "seated-calf-raise-machine",
    name: "Seated Calf Raise Machine",
    category: "Legs",
    movementRoles: ["CalfRaise"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // ==========================================================
  // Core
  // ==========================================================

  {
    id: "cable-woodchop",
    name: "Cable Woodchop",
    category: "Core",
    movementRoles: ["CoreRotation"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    repCounting: "PerSide",
    guidance: {
      setup: [
        "Set the cable around chest height and stand sideways with enough distance for steady tension.",
        "Hold the handle with both hands, soften the knees, and brace your trunk.",
      ],
      execution: [
        "Rotate through the upper trunk while guiding the handle across the body.",
        "Return slowly without allowing the cable to pull you out of position.",
      ],
      techniqueCues: ["Move the ribcage and arms together.", "Keep the hips controlled instead of spinning on the feet."],
      commonMistakes: ["Pulling mostly with the arms.", "Using momentum or excessive low-back rotation."],
      safetyConsiderations: ["Use a range you can control without back discomfort and keep clear of the cable path."],
      regressionExerciseIds: ["band-woodchop"],
    },
  },
  {
    id: "band-woodchop",
    name: "Band Woodchop",
    category: "Core",
    movementRoles: ["CoreRotation"],
    requiredEquipment: ["ResistanceBands"],
    requiredCapabilities: ["HighAnchor"],
    sets: 3,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
    repCounting: "PerSide",
  },
  {
    id: "ab-crunch-machine",
    name: "Ab Crunch Machine",
    category: "Core",
    movementRoles: ["CoreFlexion"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
    guidance: {
      setup: [
        "Adjust the seat and pads so the machine's pivot matches your trunk and the restraints feel secure.",
        "Choose a load that allows a smooth curl without pulling with the arms.",
      ],
      execution: [
        "Bring the ribs toward the pelvis by curling the trunk against the resistance.",
        "Return with control until the abdominals lengthen without forcefully arching the back.",
      ],
      techniqueCues: ["Exhale through the curl.", "Keep the movement centered in the trunk rather than the hips."],
      commonMistakes: ["Yanking the handles with the arms.", "Using a large hip hinge instead of controlled spinal flexion."],
      safetyConsiderations: ["Use a comfortable range and stop if loaded flexion causes back pain."],
      regressionExerciseIds: ["cable-crunch", "dead-bug"],
    },
  },

  // ----------------------------------------------------------
  // Plank Progression
  // ----------------------------------------------------------

  {
    id: "plank",
    name: "Plank",
    category: "Core",
    movementRoles: ["CoreStability"],
    requiredEquipment: ["Bodyweight", "YogaMat"],
    requiredCapabilities: ["FloorSpace"],
    sets: 3,
    repMin: 30,
    repMax: 60,
    increment: 0,
    progressionType: "Duration",
    resistanceType: "None",
    performanceType: "Duration",
    nextVariationId:
      "long-lever-plank",
  },
  {
    id: "long-lever-plank",
    name: "Long-Lever Plank",
    category: "Core",
    movementRoles: ["CoreStability"],
    requiredEquipment: ["Bodyweight", "YogaMat"],
    requiredCapabilities: ["FloorSpace"],
    sets: 3,
    repMin: 20,
    repMax: 45,
    increment: 0,
    progressionType: "Duration",
    resistanceType: "None",
    performanceType: "Duration",
    nextVariationId:
      "weighted-plank",
  },
  {
    id: "weighted-plank",
    name: "Weighted Plank",
    category: "Core",
    movementRoles: ["CoreStability"],
    requiredEquipment: [
      "Bodyweight",
      "YogaMat",
      "WeightPlate",
    ],
    requiredCapabilities: ["FloorSpace"],
    sets: 3,
    repMin: 30,
    repMax: 60,
    increment: 5,

    // Temporarily retained for backwards compatibility.
    progressionType: "Load",

    resistanceType: "Weight",
    performanceType: "Duration",
  },

  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "Core",
    movementRoles: ["CoreStability"],
    requiredEquipment: ["Bodyweight", "YogaMat"],
    requiredCapabilities: ["FloorSpace"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
    repCounting: "PerSide",
    guidance: {
      setup: [
        "Lie on your back with hips and knees bent to 90 degrees and arms reaching upward.",
        "Gently brace so your ribs stay down and your lower back remains supported.",
      ],
      execution: [
        "Slowly extend the opposite arm and leg without losing trunk position.",
        "Return with control, then repeat on the other side.",
      ],
      techniqueCues: ["Exhale as the limbs move away.", "Use a smaller reach to preserve rib and pelvis position."],
      commonMistakes: ["Arching the low back to reach farther.", "Moving quickly enough that balance replaces muscular control."],
      safetyConsiderations: ["Shorten the lever or keep the arms still if the low back cannot remain comfortable."],
      regressionExerciseIds: ["plank"],
      progressionExerciseIds: ["lying-leg-raise"],
    },
  },

  {
    id: "cable-crunch",
    name: "Cable Crunch",
    category: "Core",
    movementRoles: ["CoreFlexion"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    category: "Core",
    movementRoles: ["CoreHipFlexion"],
    requiredEquipment: ["Bodyweight", "PullUpBar"],
    requiredCapabilities: ["PullUpBarInstalled"],
    sets: 3,
    repMin: 8,
    repMax: 15,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
  },
  {
    id: "lying-leg-raise",
    name: "Lying Leg Raise",
    category: "Core",
    movementRoles: ["CoreHipFlexion"],
    requiredEquipment: ["Bodyweight", "YogaMat"],
    requiredCapabilities: ["FloorSpace"],
    sets: 3,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
  },
];

export function getExerciseDisplayName(
  exerciseDefinitionId: string | undefined,
  fallbackName: string
) {
  if (!exerciseDefinitionId) {
    return fallbackName;
  }

  return (
    exerciseLibrary.find(
      (exercise) =>
        exercise.id === exerciseDefinitionId
    )?.name ?? fallbackName
  );
}
