import type {
  ExerciseDefinition,
} from "./types";

// ============================================================
// Built-In Exercise Library
// ============================================================
//
// Programming values below come from the Fitness OS
// spreadsheet DATA_Exercises table.
//
// Exercises that existed in the app but were not defined
// in the spreadsheet are preserved without progression
// settings. We can configure those separately later.
//
// Metric model:
//
// resistanceType
//   None       = bodyweight / no external resistance
//   Weight     = conventional external load
//   Assistance = external assistance
//   Band       = resistance-band loading
//
// performanceType
//   Reps       = performance measured in repetitions
//   Duration   = performance measured in seconds
//
// progressionType is temporarily retained for backwards
// compatibility with the existing progression engine.
// ============================================================

export const exerciseLibrary: ExerciseDefinition[] = [
  // ==========================================================
  // Chest
  // ==========================================================

  {
    id: "chest-press-machine",
    name: "Chest Press Machine",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "incline-chest-press-machine",
    name: "Incline Chest Press Machine",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "dumbbell-chest-press",
    name: "Dumbbell Chest Press",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["Dumbbells", "Bench"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // ----------------------------------------------------------
  // Push-Up Progression
  // ----------------------------------------------------------

  {
    id: "push-ups",
    name: "Push-Ups",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 8,
    repMax: 15,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
    nextVariationId:
      "feet-elevated-push-ups",
  },
  {
    id: "feet-elevated-push-ups",
    name: "Feet-Elevated Push-Ups",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["Bodyweight", "Bench"],
    sets: 3,
    repMin: 8,
    repMax: 15,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
    nextVariationId:
      "weighted-push-ups",
  },
  {
    id: "weighted-push-ups",
    name: "Weighted Push-Ups",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // Not defined in the spreadsheet.
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["GymMachines", "Bench"],
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    category: "Chest",
    movementRoles: ["HorizontalPush"],
    requiredEquipment: ["Dumbbells", "Bench"],
  },
  {
    id: "chest-fly",
    name: "Chest Fly",
    category: "Chest",
    movementRoles: ["Accessory"],
    requiredEquipment: ["GymMachines"],
  },

  // ==========================================================
  // Back
  // ==========================================================

  {
    id: "seated-row",
    name: "Seated Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "cable-row",
    name: "Cable Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "one-arm-dumbbell-row",
    name: "One-Arm Dumbbell Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["Dumbbells", "Bench"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "backpack-row",
    name: "Backpack Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
  },
  {
    id: "band-row",
    name: "Band Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["ResistanceBands"],
    requiredCapabilities: ["HighAnchor"],
    sets: 3,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    category: "Back",
    movementRoles: ["VerticalPull"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "assisted-pull-up",
    name: "Assisted Pull-Up",
    category: "Back",
    movementRoles: ["VerticalPull"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Assistance",
    resistanceType: "Assistance",
    performanceType: "Reps",
  },
  {
    id: "band-pulldown",
    name: "Band Pulldown",
    category: "Back",
    movementRoles: ["VerticalPull"],
    requiredEquipment: ["ResistanceBands"],
    requiredCapabilities: ["HighAnchor"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
  },

  // Not defined in the spreadsheet.
  {
    id: "barbell-row",
    name: "Barbell Row",
    category: "Back",
    movementRoles: ["HorizontalPull"],
    requiredEquipment: ["GymMachines"],
  },

  // ==========================================================
  // Shoulders
  // ==========================================================

  {
    id: "shoulder-press-machine",
    name: "Shoulder Press Machine",
    category: "Shoulders",
    movementRoles: ["VerticalPush"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    category: "Shoulders",
    movementRoles: ["VerticalPush"],
    requiredEquipment: ["Dumbbells"],
    sets: 2,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "band-shoulder-press",
    name: "Band Shoulder Press",
    category: "Shoulders",
    movementRoles: ["VerticalPush"],
    requiredEquipment: ["ResistanceBands"],
    sets: 2,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
  },
  {
    id: "lateral-raise-machine",
    name: "Lateral Raise Machine",
    category: "Shoulders",
    movementRoles: ["Accessory"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 12,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    category: "Shoulders",
    movementRoles: ["Accessory"],
    requiredEquipment: ["Dumbbells"],
    sets: 2,
    repMin: 12,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    category: "Shoulders",
    movementRoles: ["Accessory"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 12,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "cable-face-pull",
    name: "Cable Face Pull",
    category: "Shoulders",
    movementRoles: ["Accessory"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 12,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // Not defined in the spreadsheet.
  {
    id: "overhead-press",
    name: "Overhead Press",
    category: "Shoulders",
    movementRoles: ["VerticalPush"],
    requiredEquipment: ["GymMachines"],
  },

  // ==========================================================
  // Arms
  // ==========================================================

  {
    id: "biceps-curl-machine",
    name: "Biceps Curl Machine",
    category: "Arms",
    movementRoles: ["Accessory"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "dumbbell-curl",
    name: "Dumbbell Curl",
    category: "Arms",
    movementRoles: ["Accessory"],
    requiredEquipment: ["Dumbbells"],
    sets: 2,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "triceps-press-machine",
    name: "Triceps Press Machine",
    category: "Arms",
    movementRoles: ["Accessory"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "cable-pressdown",
    name: "Cable Pressdown",
    category: "Arms",
    movementRoles: ["Accessory"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  {
    id: "band-biceps-curl",
    name: "Band Biceps Curl",
    category: "Arms",
    movementRoles: ["Accessory"],
    requiredEquipment: ["ResistanceBands"],
    sets: 2,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
  },
  {
    id: "band-overhead-triceps-extension",
    name: "Band Overhead Triceps Extension",
    category: "Arms",
    movementRoles: ["Accessory"],
    requiredEquipment: ["ResistanceBands"],
    requiredCapabilities: ["HighAnchor"],
    sets: 2,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
  },

  // Not defined in the spreadsheet.
  {
    id: "triceps-pushdown",
    name: "Triceps Pushdown",
    category: "Arms",
    movementRoles: ["Accessory"],
    requiredEquipment: ["GymMachines"],
  },
  {
    id: "biceps-curl",
    name: "Biceps Curl",
    category: "Arms",
    movementRoles: ["Accessory"],
    requiredEquipment: ["Dumbbells"],
  },

  // ==========================================================
  // Legs
  // ==========================================================

  {
    id: "leg-press",
    name: "Leg Press",
    category: "Legs",
    movementRoles: ["Squat", "SquatGlute"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 10,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "hack-squat-pendulum-squat",
    name: "Hack Squat / Pendulum Squat",
    category: "Legs",
    movementRoles: ["Squat", "SquatGlute"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 10,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    category: "Legs",
    movementRoles: ["Squat"],
    requiredEquipment: ["Dumbbells"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "reverse-lunge",
    name: "Reverse Lunge",
    category: "Legs",
    movementRoles: ["Squat"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
    repCounting: "PerSide",
  },
  {
    id: "leg-curl",
    name: "Leg Curl",
    category: "Legs",
    movementRoles: ["KneeFlexion"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "dumbbell-rdl",
    name: "Dumbbell RDL",
    category: "Legs",
    movementRoles: ["HipHinge"],
    requiredEquipment: ["Dumbbells"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    category: "Legs",
    movementRoles: ["SquatGlute"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
  },
  {
    id: "band-good-morning",
    name: "Band Good Morning",
    category: "Legs",
    movementRoles: ["HipHinge"],
    requiredEquipment: ["ResistanceBands"],
    requiredCapabilities: ["FloorSpace"],
    sets: 3,
    repMin: 10,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "Band",
    performanceType: "Reps",
  },
  {
    id: "hip-abductor",
    name: "Hip Abductor",
    category: "Legs",
    movementRoles: ["HipStability"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 12,
    repMax: 20,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "side-lying-hip-abduction",
    name: "Side-Lying Hip Abduction",
    category: "Legs",
    movementRoles: ["HipStability"],
    requiredEquipment: ["Bodyweight", "YogaMat"],
    requiredCapabilities: ["FloorSpace"],
    sets: 2,
    repMin: 12,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
  },
  {
    id: "side-lying-hip-adduction",
    name: "Side-Lying Hip Adduction",
    category: "Legs",
    movementRoles: ["Adduction"],
    requiredEquipment: ["Bodyweight", "YogaMat"],
    requiredCapabilities: ["FloorSpace"],
    sets: 2,
    repMin: 12,
    repMax: 20,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
  },
  {
    id: "hip-adductor",
    name: "Hip Adductor",
    category: "Legs",
    movementRoles: ["Adduction"],
    requiredEquipment: ["GymMachines"],
    sets: 2,
    repMin: 12,
    repMax: 20,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // Not defined in the spreadsheet.
  {
    id: "barbell-squat",
    name: "Barbell Squat",
    category: "Legs",
    movementRoles: ["Squat", "SquatGlute"],
    requiredEquipment: ["GymMachines"],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    category: "Legs",
    movementRoles: ["HipHinge"],
    requiredEquipment: ["GymMachines"],
  },
  {
    id: "calf-raise",
    name: "Calf Raise",
    category: "Legs",
    movementRoles: ["Accessory"],
    requiredEquipment: ["Bodyweight"],
  },

  // ==========================================================
  // Core
  // ==========================================================

  {
    id: "cable-woodchop",
    name: "Cable Woodchop",
    category: "Core",
    movementRoles: ["Core"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 12,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },
  {
    id: "ab-crunch-machine",
    name: "Ab Crunch Machine",
    category: "Core",
    movementRoles: ["Core"],
    requiredEquipment: ["GymMachines"],
    sets: 3,
    repMin: 10,
    repMax: 15,
    increment: 5,
    progressionType: "Load",
    resistanceType: "Weight",
    performanceType: "Reps",
  },

  // ----------------------------------------------------------
  // Plank Progression
  // ----------------------------------------------------------

  {
    id: "plank",
    name: "Plank",
    category: "Core",
    movementRoles: ["Core"],
    requiredEquipment: ["Bodyweight", "YogaMat"],
    requiredCapabilities: ["FloorSpace"],
    sets: 3,
    repMin: 30,
    repMax: 60,
    increment: 0,
    progressionType: "Duration",
    resistanceType: "None",
    performanceType: "Duration",
    nextVariationId:
      "long-lever-plank",
  },
  {
    id: "long-lever-plank",
    name: "Long-Lever Plank",
    category: "Core",
    movementRoles: ["Core"],
    requiredEquipment: ["Bodyweight", "YogaMat"],
    requiredCapabilities: ["FloorSpace"],
    sets: 3,
    repMin: 20,
    repMax: 45,
    increment: 0,
    progressionType: "Duration",
    resistanceType: "None",
    performanceType: "Duration",
    nextVariationId:
      "weighted-plank",
  },
  {
    id: "weighted-plank",
    name: "Weighted Plank",
    category: "Core",
    movementRoles: ["Core"],
    requiredEquipment: ["Bodyweight"],
    sets: 3,
    repMin: 30,
    repMax: 60,
    increment: 5,

    // Temporarily retained for backwards compatibility.
    progressionType: "Load",

    resistanceType: "Weight",
    performanceType: "Duration",
  },

  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "Core",
    movementRoles: ["Core"],
    requiredEquipment: ["Bodyweight", "YogaMat"],
    requiredCapabilities: ["FloorSpace"],
    sets: 3,
    repMin: 8,
    repMax: 12,
    increment: 0,
    progressionType: "Reps",
    resistanceType: "None",
    performanceType: "Reps",
    repCounting: "PerSide",
  },

  // Not defined in the spreadsheet.
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    category: "Core",
    movementRoles: ["Core"],
    requiredEquipment: ["GymMachines"],
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    category: "Core",
    movementRoles: ["Core"],
    requiredEquipment: ["Bodyweight"],
  },
];